export const FETCHING_LIST = "FETCHING_LIST";
export const FETCH_LIST = "FETCH_LIST";
export const FETCH_ERROR_LIST = "FETCH_ERROR_LIST";
export const FETCHING_DETAIL = "FETCHING_DETAIL";
export const FETCH_DETAIL = "FETCH_DETAIL";
export const FETCH_ERROR_DETAIL = "FETCH_ERROR_DETAIL";
